### ISSUE TITLE
町丁の区切りの表記ゆれについて

### ISSUE THREAD

**Issue by yonaka** [t-sagara/jageocoder#15]
jageocoderのreverse geocodingを利用させて頂いた動画を作成しました。ありがとうございます。
その際に少し気づいたことがありましたのでご報告します。

https://youtu.be/-v2VojfDfzA?t=34

　動画の0:36あたりから
`埼玉県 越谷市 千間台東 三丁目 28番` (139.7798952999999926 35.9305893000000012 --level=7)
`埼玉県 越谷市 千間台 東三丁目 28番` (139.7798431999999877 35.9306677000000008 --level=7)
の二種類の表記が出てきます。
　返ってきたリストを見るとxとyが同じで上のように区切りだけ異なるものが2つ返ってきています。動画では[0]のものを使用し、`" ".join()`でくっつけています。

`埼玉県 越谷市 千間台東 四丁目` (139.7793651000000068 35.9313635000000033 --level=7)
`埼玉県 越谷市 千間台 東四丁目 835番地` (139.7793499999999938 35.9313837999999990 --level=7)
や
`埼玉県 春日部市 粕壁 東五丁目 15番` (139.7647573000000136 35.9760180000000034 --level=7)
`埼玉県 春日部市 粕壁東 五丁目 15番` (139.7647076000000084 35.9761112999999995 --level=7)

というパターンもありました。

　大きな問題ではないと思いますが、ご参考まで。

**Comment by t-sagara** [comment]
> 　大きな問題ではないと思いますが、ご参考まで。

ご利用・コメントありがとうございます。自治体が決めている住所は「千間台東四丁目」のように丁目を分割しません。しかしこのままでは「千間台」を検索しても「該当なし」になってしまうため、20年以上前から住所辞書を作る際にこちらの都合で「千間台／東四丁目」と区切ってきました。

しかし2022年5月にデジタル庁が公開した「アドレス・ベース・レジストリ」では、これを「千間台東／四丁目」と区切るというルールを採用しました。そのため、現在は国交省のデータをもとにこちらで作成したデータと、デジ庁が公開しているデータという区切り位置の違う2通りの候補が返ってきます。

当面解決の見込みがないため、お手数をおかけしますが「join でくっつける」という対応で引き続きお願いいたします。

**Comment by yonaka** [comment]
なるほど、そういうことだったんですね。
アプリ側で「丁目」が入っているときに何か回避できるか考えてみます。
ありがとうございます。
