### ISSUE TITLE
浜松市行政区再編の対応について

### ISSUE THREAD

**Issue by kinsho-stb** [t-sagara/jageocoder#19]
お世話になっております。

## 内容
2024/01/01から実施される浜松市行政区再編について、データ更新等の対応実施される予定はございますでしょうか？

## 参考
https://www.city.hamamatsu.shizuoka.jp/kikaku/kuseido/index.html

**Comment by t-sagara** [comment]
@kinsho-stb 情報ありがとうございます。国土地理院の住居表示住所も 1/1 づけで更新されましたので、浜松市の再編に対応したデータファイルを作成する予定です。

**Comment by t-sagara** [comment]
@kinsho-stb 浜松市の区の再編を反映した辞書を公開しました。
https://www.info-proto.com/static/jageocoder/latest/
