### ISSUE TITLE
Python3.12への対応

### ISSUE THREAD

**Issue by KatHaruto** [t-sagara/jageocoder#20]
Python3.12で動作させようとすると依存関係にあるpycapnp(1.3.x)のインストールでエラーが発生します。

pycapnpでは直近の対応があったみたいなのでご確認いただきたいです。
https://github.com/capnproto/pycapnp/pull/330

**Comment by t-sagara** [comment]
@kinshotomoya PortableTab==0.3.4 で Python 3.12 に対応しました。
